flutter_native_splash:
    color: "#000000"
name: base_flutter_framework
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+16

environment:
  sdk: ">=2.14.0 <3.0.0"

dependency_overrides:
  meta: 1.3.0



dev_dependencies:
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/img_splash.png"
  remove_alpha_ios: true

dependencies:

  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  json_annotation:
  flutter_bloc: ^8.1.1
  html_unescape: ^2.0.0
  flutter_linkify: ^5.0.2
  equatable: 
  intl:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.2
  get: ^4.1.3
  wave: ^0.2.0
  fluttertoast: ^8.0.3
  flutter_easyloading: ^3.0.0
  flutter_svg: 
  connectivity: ^3.0.6
  rxdart: ^0.27.2
  carousel_slider: ^4.0.0
  dots_indicator: ^2.0.0
  share: ^2.0.4
  flutter_html: ^2.2.1
  path_provider: ^2.0.11
  image_downloader: ^0.31.0
  persistent_bottom_nav_bar: ^5.0.2
  cached_network_image: ^3.1.0+1
  animated_bottom_navigation_bar: ^1.1.0
  webview_flutter: ^2.0.4
  lazy_load_scrollview: ^1.3.0
  progress_indicators: ^1.0.0
  scroll_navigation: ^1.3.2
  adaptive_dialog: ^1.2.0

  # Local data
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  #form
  reactive_forms: ^14.1.0
  modal_bottom_sheet: ^2.0.0
  flutter_datetime_picker: 1.5.1
  flutter_colorpicker: ^1.0.3
  dynamic_theme_mode: ^1.0.0
  page_transition: ^2.0.4

  
  rename: ^2.0.1
  flutter_rating_bar: ^4.0.0
  introduction_screen: ^3.1.1
  flutter_staggered_grid_view: ^0.6.2
  

  #libary service
  dio: 

  firebase_crashlytics:  #firebase crash lytic
  # firebase_dynamic_links:  #deep link
  http:  #rest api
  giphy_picker:
  # onesignal_flutter: 3.0.0-beta2 #noti 
  socket_io_client: ^2.0.0 #socket lib
  http_parser:  #http format
  package_info:
  camera: ^0.10.1
  google_ml_kit: 0.13.0
  painter: ^2.0.0
  image_picker: ^0.8.4+4
  image_cropper: ^3.0.1
  flutter_native_image: ^0.0.6+1
  sqflite: ^2.2.2
  shared_preferences: ^2.0.11
  permission_handler: ^10.2.0
  in_app_purchase: ^3.0.0
  flutter_inapp_purchase: ^5.3.1
  #Device ID
#  device_info_plus: ^3.0.1

  async: ^2.4.1

  # Wallpaper
  wallpaper: ^1.1.0
  # Url_launcher
  url_launcher: ^6.0.17
  awesome_dialog: ^3.0.2

  package_info_plus: ^3.0.2
  device_info_plus: ^8.0.0

  rating_dialog: ^2.0.3

  flutter_share: ^2.0.0
  loader_overlay: ^2.0.5
  group_radio_button: ^1.2.0
  google_mobile_ads: ^2.3.0









# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/launcher/
    - assets/fonts/
    - assets/images/
    - assets/lang/
    - assets/database.db
    
  




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
  #       
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  
